### PR TITLE
[issue 3]: Implement Application Form

### PR DESCRIPTION
**Pull request by Gehadazzam**
…some functionality of the buttons

### CODE REVIEW

**Comment by Hamdysaad20** [comment]
@Gehadazzam  once it finished let me know by assign me as a reviewer

**Comment by Hamdysaad20** [comment]
## The layout is not fully responsive. Please adjust the sections outside the div's border by using flex and flex-col. If you need further assistance with this issue, feel free to reach out to @hazem-moh . Once the adjustments are complete, please reassign me as a reviewer.

Screenshot 2024-08-18 at 12 18 23 AM
Screenshot 2024-08-18 at 12 17 57 AM

**Comment by hazem-moh** [comment]
I fixed the layout, but The inputs fields in the form may not be working because the (onChange) handlers are missing. These handlers are essential for updating the component's state when a user interacts with the input fields.

**Comment by hazem-moh** [comment]
> ## The layout is not fully responsive. Please adjust the sections outside the div's border by using flex and flex-col. If you need further assistance with this issue, feel free to reach out to . Once the adjustments are complete, please reassign me as a reviewer.
> @hazem-moh
> 
> Screenshot 2024-08-18 at 12 18 23 AM Screenshot 2024-08-18 at 12 17 57 AM

**Comment by hazem-moh** [comment]
@Gehadazzam 
Here you go the changes I my made to make sure that Layout is fully responsive :

1-Flexbox and Grid Layouts: The component now uses flex and grid properties with md: prefixes for responsive adjustments, making it more adaptable to different screen sizes.

2-Conditional Wrapping: The layout adjusts flexibly to ensure elements stack on smaller screens and align side by side on larger screens.

3-Width Adjustments: Adjusted widths of elements to ensure they occupy appropriate space on different screen sizes, making the form more usable on both mobile and desktop views.

4-Responsive Buttons and Inputs: The buttons and inputs are made responsive, ensuring they fit well within the available space without overflowing.

image
image

**Comment by Gehadazzam** [comment]
Thanks for your help Hazem, I will consider your advice on the next project.

**Comment by Hamdysaad20** [comment]
LGTM

**Pull request merged**
